const mongoose = require('mongoose');
const dotenv = require('dotenv');
const User = require('./models/User');
const Product = require('./models/Product');
const Category = require('./models/Category');

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI;

const categoriesTree = [
    {
        name: 'Men',
        slug: 'men',
        image: 'https://images.squarespace-cdn.com/content/v1/5f21b3c0862b9f38f883a002/1599064776272-LNACG049LZZHAKSA5L6H/Stylish+man+wearing+linen+shirt.jpg',
    },
    {
        name: 'Women',
        slug: 'women',
        image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=2070&auto=format&fit=crop',
        description: 'Elegant and trendy outfits for women.',
    },
    {
        name: 'Accessories',
        slug: 'accessories',
        image: 'https://img.freepik.com/premium-psd/vintage-fashion-accessories-collection-stylish-hat-pearl-jewelry-sunglasses-bags-pretty-roses_632498-28069.jpg?semt=ais_hybrid&w=740&q=80',
        description: 'Complete your look with our premium accessories.',
    },
];

const products = [
    // --- MEN'S COLLECTION (15 Items) ---
    {
        name: 'Premium Cotton Slim Fit Shirt',
        description: 'High-quality cotton shirt with a modern slim fit design. Perfect for formal and semi-formal occasions.',
        price: 2500,
        image: 'https://assets.myntassets.com/w_360,q_50,,dpr_2,fl_progressive,f_webp/assets/images/28592488/2024/3/30/eada8969-c538-4b2f-947f-cae53f140a2d1711800141335ThomasScottMenPremiumSlimFitOpaqueCasualShirt1.jpg',
        category: 'men',
        sizes: ['S', 'M', 'L', 'XL','XXL'],
        colors: ['White', 'Blue', 'Black', 'Red'],
        stock: 10,
        isFeatured: true,
    },
    {
        name: 'Classic Denim Jacket',
        description: 'A timeless denim jacket that adds a rugged touch to any outfit.',
        price: 4500,
        image: 'https://cdn11.bigcommerce.com/s-luvww1semp/images/stencil/1280x1280/products/2076/12530/as930-dnm%202020%20(2)__02752.1757416681.jpg?c=2',
        category: 'men',
        sizes: ['M', 'L', 'XL','XXL'],
        colors: ['Blue', 'Black', 'Grey'],
        stock: 9,
        isFeatured: false,
    },
    {
        name: 'Graphic Print T-Shirt',
        description: 'Soft cotton t-shirt with a unique graphic print. Casual and comfortable.',
        price: 1900,
        image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1964&auto=format&fit=crop',
        category: 'men',
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['White', 'Grey'],
        stock: 10,
        isFeatured: false,
    },
    {
        name: 'Streetwear Hoodie',
        description: 'Oversized hoodie with a kangaroo pocket and drawstring hood. Perfect for urban style.',
        price: 3900,
        image: 'https://img4.dhresource.com/webp/m/0x0/f3/albu/km/h/31/1e2efac9-1864-4ffc-9930-7ca8caec5630.jpg',
        category: 'men',
        sizes: ['M', 'L', 'XL', 'XXL'],
        colors: ['Black', 'Grey', 'Navy', 'Maroon', 'white'],
        stock: 10,
        isFeatured: true,
    },
    {
        name: 'Slim Fit Chino Pants',
        description: 'Versatile chino pants that can be dressed up or down. Stretchy fabric for comfort.',
        price: 2000,
        image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=1974&auto=format&fit=crop',
        category: 'men',
        sizes: ['S', 'M', 'L', 'XL','XXL'],
        colors: ['Beige', 'Navy', 'Olive', 'Black'],
        stock: 15,
        isFeatured: false,
    },
    {
        name: 'Formal Blazer',
        description: 'Blazer tailored for a professional look. Ideal for business meetings and events.',
        price: 5000,
        image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=2071&auto=format&fit=crop',
        category: 'men',
        sizes: ['S', 'M', 'L', 'XL','XXL'],
        colors: ['Navy', 'Black', 'Grey', 'Brown', 'Beige'],
        stock: 10,
        isFeatured: true,
    },
    {
        name: 'Casual Plaid Shirt',
        description: 'Comfortable plaid shirt made from flannel material. Great for layering.',
        price: 2200,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNHZfWIOsBeOfowsm-oO4qw_yZyAG64SMeFQ&s',
        category: 'men',
        sizes: ['M', 'L', 'XL','XXL'],
        colors: ['Red', 'Blue', 'Green'],
        stock: 15,
        isFeatured: false,
    },
    {
        name: 'Leather Jacket',
        description: 'Genuine leather jacket with motorcycle styling. Durable and stylish.',
        price: 5000,
        image: 'https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?q=80&w=1995&auto=format&fit=crop',
        category: 'men',
        sizes: ['M', 'L', 'XL','XXL'],
        colors: ['Black', 'Brown'],
        stock: 10,
        isFeatured: true,
    },
    {
        name: 'Polo T-Shirt',
        description: 'Classic polo t-shirt with ribbed collar and cuffs. Breathable fabric.',
        price: 2800,
        image: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?q=80&w=2071&auto=format&fit=crop',
        category: 'men',
        sizes: ['S', 'M', 'L', 'XL','XXL'],
        stock: 20,
        isFeatured: false,
    },
    {
        name: 'Cargo Pants',
        description: 'Functional cargo pants with multiple pockets. rugged and practical.',
        price: 3000,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4iRIZxxWVaeht7uijYcMuNUnL0Bk53XuOTQ&s',
        category: 'men',
        sizes: ['M', 'L', 'XL','XXL'],
        colors: ['Olive', 'Khaki', 'Black', 'Navy', 'Coffee', 'blue'],
        stock: 15,
        isFeatured: false,
    },
    {
        name: 'Baggy Jeans',
        description: 'Comfortable and stylish jeans perfect for everyday wear',
        price: 3800,
        image: 'https://assets.ajio.com/medias/sys_master/root/20240410/fGws/6615e91c16fd2c6e6aa81f68/-1117Wx1400H-467153683-grey-MODEL3.jpg',
        category: 'men',
        sizes: ['S', 'M', 'L', 'XL','XXL'],
        colors: ['Blue', 'Black', 'Grey', 'navy', 'washed blue'],
        stock: 13,
        isFeatured: true,
    },
    {
        name: 'Joggers',
        description: 'Comfortable joggers for casual wear.',
        price: 3000,
        image: 'https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/18/7268283/1.jpg?1587',
        category: 'men',
        sizes: ['S', 'M', 'L', 'XL','XXL'],
        colors: ['Black', 'Brown', 'Grey', 'Navy', 'Olive'],
        stock: 20,
        isFeatured: false,
    },
    {
        name: 'Crew Neck Sweater',
        description: 'Basic crew neck sweater in a versatile grey color.',
        price: 2500,
        image: 'https://naadam.co/cdn/shop/files/The-Original-Cashmere-Crewneck-Sweater-Men_s-_CO_---Cherry-Red_6398.jpg?v=1765296715&width=2376',
        category: 'men',
        sizes: ['M', 'L', 'XL','XXL'],
        colors: ['Red', 'Blue', 'Green', 'black', 'white', 'grey'],
        stock: 10,
        isFeatured: false,
    },
    {
        name: 'Distressed Skinny Jeans',
        description: 'Trendy distressed jeans with a skinny fit. Stretch denim.',
        price: 3500,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQipvvGEv1s0BrrDP_PemZGQ7JwWP55ARDdww&s',
        category: 'men',
        sizes: ['S', 'M', 'L', 'XL','XXL'],
        colors: ['Blue', 'Black'],
        stock: 25,
        isFeatured: false,
    },
    {
        name: 'Winter Parka',
        description: 'Heavy duty winter parka with faux fur hood trim. Water resistant.',
        price: 6500,
        image: 'https://arctic-bay.ca/cdn/shop/collections/DSC_1866_1200x1200.jpg?v=1710628377',
        category: 'men',
        sizes: ['M', 'L', 'XL','XXL'],
        colors: ['Black', 'Navy', 'Olive'],
        stock: 15,
        isFeatured: true,
    },

    // --- WOMEN'S COLLECTION (15 Items) ---
    {
        name: 'Floral Summer Dress',
        description: 'Lightweight and breathable floral dress, perfect for summer outings.',
        price: 2000,
        image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1946&auto=format&fit=crop',
        category: 'women',
        sizes: ['XS', 'S', 'M', 'L','XL'],
        stock: 20,
        isFeatured: true,
    },
    {
        name: 'Elegant Evening Gown',
        description: 'A stunning evening gown for special occasions. Features a sleek silhouette and premium fabric.',
        price: 2500,
        image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1908&auto=format&fit=crop',
        category: 'women',
        sizes: ['S', 'M', 'L','XL'],
        stock: 15,
        isFeatured: true,
    },
    {
        name: 'Chic Crop Top',
        description: 'Trendy crop top that pairs perfectly with high-waisted jeans or skirts.',
        price: 1800,
        image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=2005&auto=format&fit=crop',
        category: 'women',
        sizes: ['XS', 'S', 'M', 'L'],
        stock: 10,
        isFeatured: false,
    },
    {
        name: 'Bohemian Maxi Skirt',
        description: 'Flowy maxi skirt with a bohemian print. Comfortable elastic waistband.',
        price: 1800,
        image: 'https://wildroseboho.com/cdn/shop/files/43.3_1000x.jpg?v=1712406416',
        category: 'women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Red', 'Blue', 'Green', 'Yellow', 'Pink', 'White', 'Black'],
        stock: 9,
        isFeatured: false,
    },
    {
        name: 'Traditional Cotton Kurti',
        description: 'Beautiful traditional kurti made from breathable cotton fabric. Intricate embroidery details.',
        price: 2800,
        image: 'https://assets0.mirraw.com/images/13522092/image_long_webp.webp?1757930710',
        category: 'women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Red', 'Blue', 'Green', 'Yellow', 'Pink'],
        stock: 10,
        isFeatured: true,
    },
    {
        name: 'High-Waist Skinny Jeans',
        description: 'Flattering high-waist skinny jeans with perfectly placed rips. Premium denim.',
        price: 3200,
        image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1887&auto=format&fit=crop',
        category: 'women',
        sizes: ['S', 'M', 'L', 'XL'],
        stock: 15,
        isFeatured: false,
    },
    {
        name: 'Cozy Knit Sweater',
        description: 'Warm and cozy knit sweater for chilly days. Oversized fit for maximum comfort.',
        price: 3500,
        image: 'https://m.media-amazon.com/images/I/71H5iIbR4-L._AC_UY1000_.jpg',
        category: 'women',
        sizes: ['S', 'M', 'L','XL'],
        colors: ['White', 'Black', 'Grey'],
        stock: 20,
        isFeatured: true,
    },
    {
        name: 'Silk Blouse',
        description: 'Elegant silk blouse suitable for office wear or formal dinners.',
        price: 1200,
        image: 'https://m.media-amazon.com/images/I/61wAV4MQwUL._AC_SL1500_.jpg',
        category: 'women',
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['White', 'olive', 'Black', 'Red', 'Navy', 'pink'],
        stock: 5,
        isFeatured: false,
    },
    {
        name: 'Denim Shorts',
        description: 'Casual denim shorts with a raw hem. Must-have for summer wardrobes.',
        price: 1200,
        image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?q=80&w=2070&auto=format&fit=crop',
        category: 'women',
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Blue', 'Black', 'Grey'],
        stock: 10,
        isFeatured: false,
    },
    {
        name: 'Velvet Party Dress',
        description: 'Luxurious velvet dress that makes a statement at any party.',
        price: 5000,
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1966&auto=format&fit=crop',
        category: 'women',
        sizes: ['S', 'M', 'L','XL'],
        colors: ['Red', 'Black', 'Green'],
        stock: 15,
        isFeatured: true,
    },
    {
        name: 'Pleated Midi Skirt',
        description: 'Classic pleated midi skirt in a metallic finish.',
        price: 1700,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKwBUcnEfzd97TlRJWiASai-hTsIGywuQu0A&s',
        category: 'women',
        sizes: ['S', 'M', 'L','XL'],
        colors: ['Silver', 'Gold', 'Rose Gold', 'Black', 'Navy'],
        stock: 10,
        isFeatured: false,
    },
    {
        name: 'Oversized Wool Coat',
        description: 'Stylish oversized wool coat to keep you warm and fashionable.',
        price: 9000,
        image: 'https://saisonstudio.com/cdn/shop/files/D2D59A79-86E1-45DF-9EA6-44A3A7F982EC_grande.jpg?v=1735416735',
        category: 'women',
        sizes: ['M', 'L', 'XL'],
        stock: 10,
        isFeatured: true,
    },
    {
        name: 'Linen Trousers',
        description: 'Breathable linen trousers perfect for a relaxed and airy look.',
        price: 1000,
        image: 'https://www.cottontraders.com/dw/image/v2/BCDM_PRD/on/demandware.static/-/Sites-cotton-master-catalog/default/dw0f7f10c0/images/original/AC16147W_original_neutral_duck-egg_230187.jpg?sw=549',
        category: 'women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Beige', 'White', 'Olive', 'Navy', 'Grey'],
        stock: 8,
        isFeatured: false,
    },
    {
        name: 'Wrap Front Blouse',
        description: 'Flattering wrap front blouse with long sleeves.',
        price: 1900,
        image: 'https://images.stylishop.com/cdn-cgi/image/format=avif/media/catalog/product/7004044206/images/7004044206_1.jpg?v=1',
        category: 'women',
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['White', 'Maroon', 'Black', 'Red', 'Navy', 'Olive'],
        stock: 5,
        isFeatured: false,
    },
    {
        name: 'Puffer Jacket',
        description: 'Warm puffer jacket in a vibrant color. Insulated for cold weather.',
        price: 3500,
        image: 'https://canadagoose.com.au/cdn/shop/files/2088WT_9392_a.jpg?v=1760935520',
        category: 'women',
        sizes: ['S', 'M', 'L'],
        colors: ['Red', 'Blue', 'Green', 'Yellow', 'Pink'],
        stock: 9,
        isFeatured: false,
    },

    // --- ACCESSORIES (5 Items) ---
    {
        name: 'Leather Minimalist Watch',
        description: 'Sophisticated minimalist watch with a genuine leather strap.',
        price: 4000,
        image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=1999&auto=format&fit=crop',
        category: 'accessories',
        sizes: ['Universal'],
        stock: 25,
        isFeatured: false,
    },
    {
        name: 'Classic Aviator Sunglasses',
        description: 'Protective and stylish aviator sunglasses with a gold frame.',
        price: 3500,
        image: 'https://static5.lenskart.com/media/catalog/product/pro/1/thumbnail/1080x1080/9df78eab33525d08d6e5fb8d27136e95//v/i/blue-gradient-gunmetal-full-rim-aviator-vincent-chase-polarized-metal-classics-vc-s17403-c2-sunglasses_p_dsc4774.jpg',
        category: 'accessories',
        sizes: ['Universal'],
        stock: 100,
        isFeatured: true,
    },
    {
        name: 'Premium Leather Wallet',
        description: 'Handcrafted genuine leather wallet with RFID protection and multiple card slots.',
        price: 4500,
        image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=1974&auto=format&fit=crop',
        category: 'accessories',
        sizes: ['Universal'],
        stock: 60,
        isFeatured: false,
    },
    {
        name: 'Silk Patterned Scarf',
        description: 'Luxurious silk scarf with a unique hand-painted floral pattern. Perfect for any season.',
        price: 5000,
        image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1935&auto=format&fit=crop',
        category: 'accessories',
        sizes: ['Universal'],
        stock: 45,
        isFeatured: true,
    },
    {
        name: 'Urban Canvas Backpack',
        description: 'Durable and stylish canvas backpack with a dedicated laptop compartment and waterproof lining.',
        price: 6000,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1887&auto=format&fit=crop',
        category: 'accessories',
        sizes: ['Universal'],
        stock: 20,
        isFeatured: false,
    },
    {
    name: 'Stainless Steel Chain Bracelet',
    description: 'Modern stainless steel chain bracelet with a polished finish. Durable, stylish, and suitable for daily wear.',
    price: 2800,
    image: 'https://i5.walmartimages.com/seo/3-5-7-9-11mm-Silver-Stainless-Steel-Curb-Cuban-Chain-Bracelet-for-Men-Women-7-inch-10-inch_39c176d9-cccf-477d-9ab8-245f56be7c29.45beee4a82be08f03c8f935698b0db76.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF',
    category: 'accessories',
    sizes: ['Universal'],
    stock: 40,
    isFeatured: false,
},
{
    name: 'Unisex Woolen Beanie',
    description: 'Soft and warm woolen beanie designed for comfort and everyday casual style during cold seasons.',
    price: 1800,
    image: 'https://wiesmade.com/cdn/shop/files/All_color_1_Beanie_100_wool_made_in_usa.jpg?v=1736642551&width=1445',
    category: 'accessories',
    sizes: ['Universal'],
    stock: 55,
    isFeatured: false,
},
{
    name: 'Slim Leather Belt',
    description: 'Premium slim leather belt with a classic metal buckle, perfect for both formal and casual outfits.',
    price: 2200,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT13VH7N6tVHfEOAuKL1X8cDvnjeX_cu-Hc7g&s',
    category: 'accessories',
    sizes: ['Universal'],
    stock: 35,
    isFeatured: true,
},
{
    name: 'Gold-plated  Chain Necklace Set',
    description: 'Elegant set of 12 simple gold chain necklaces with multilayer and choker styles, perfect for women’s everyday or party wear.',
    price: 4500,
    image: 'https://i5.walmartimages.com/seo/12Pcs-Simple-Gold-Chain-Necklace-Multilayer-Choker-Necklaces-Set-for-Women_8270a7bb-37ea-4e1e-b055-92095da8bb7b.2e6fbfcd9108348a49626d3248170d47.jpeg',
    category: 'accessories',
    sizes: ['Universal'],
    stock: 50,
    isFeatured: true,
},

];

const importData = async () => {
    try {
        await Category.deleteMany();
        await Product.deleteMany();
        // optionally await User.deleteMany(); if you want to reset users too, but usually not needed for product fixes

        await Category.insertMany(categoriesTree);
        await Product.insertMany(products);

        console.log('Data Imported!');
        process.exit();
    } catch (error) {
        console.error(`${error}`);
        process.exit(1);
    }
};

mongoose.connect(MONGODB_URI).then(() => {
    importData();
});
